version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  server:
    build: ./server
    ports:
      - 3000:3000
      - 5000:5000
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - 8080:8080
    depends_on:
      - server

volumes:
  mongodb-data:
